Scripts: Expand on the format flag

diff --git a/scripts/info/show_bat b/scripts/info/show_bat
--- a/scripts/info/show_bat
+++ b/scripts/info/show_bat
@@ -726,7 +726,7 @@ get_bat_time()
     bat_time="$(multi "${bat_time}" "3600")"
     bat_time="$(round "0" "${bat_time}")"
 
-    if ((bat_time != 0)); then
+    ((bat_time != 0)) && {
         hours="$((bat_time / 60 / 60 % 24))"
         mins="$((bat_time / 60 % 60))"
         secs="$(((bat_time % 60) % 60))"
@@ -735,11 +735,8 @@ get_bat_time()
         ((mins == 0)) && unset mins
 
         bat_time="${hours:+${hours}h }${mins:+${mins}m }${secs}s"
-    else
-        bat_time="0h 0m 0s"
-    fi
-
-    bat_info["bat_time"]="${bat_time}"
+        bat_info["bat_time"]="${bat_time}"
+    }
 }
 
 print_usage()
@@ -785,7 +782,7 @@ Examples:
     \$ ${0##*/} bat_condition bat_temp
 
     Print battery percentage and time remaining with a format string:
-    \$ ${0##*/} --format '{} | {}' percent bat_time
+    \$ ${0##*/} --format '{bat_percent}{bat_time? | {bat_time}}'
 
 Misc:
     If notify-send is not installed, then the script will
@@ -800,7 +797,43 @@ get_args()
             "--stdout") : "${out:=stdout}" ;;
             "--json") : "${out:=json}" ;;
             "-r"|"--raw") : "${out:=raw}" ;;
-            "-f"|"--format") [[ "$2" ]] && { str_format="$2"; shift; } ;;
+            "-f"|"--format")
+                [[ "$2" ]] && {
+                    declare -A uniq
+
+                    : "${out:=string}"
+                    str_format="$2"
+
+                    tmp="${str_format}"
+                    regex_1='{([a-zA-Z]+)\?[^{]*{([a-zA-Z]+)}'
+                    regex_2='({)([a-zA-Z0-9_]+)'
+
+                    # First pass
+                    while [[ "${tmp}" =~ ${regex_1} ]]; do
+                        tmp="${tmp/${BASH_REMATCH[0]}}"
+                        [[ "${BASH_REMATCH[1]}" != "${BASH_REMATCH[2]}" ]] && {
+                            printf "Invalid format: %s != %s\\n" \
+                                   "${BASH_REMATCH[1]}" \
+                                   "${BASH_REMATCH[2]}" >&2
+                            exit 1
+                        }
+                    done
+
+                    tmp="${str_format}"
+
+                    # Second pass
+                    while [[ "${tmp}" =~ ${regex_2} ]]; do
+                        [[ ! "${uniq[${BASH_REMATCH[2]}]}" ]] && {
+                            uniq["${BASH_REMATCH[2]}"]="1"
+                            func+=("${BASH_REMATCH[2]}")
+                        }
+                        tmp="${tmp/${BASH_REMATCH[2]}}"
+                    done
+
+                    shift
+                }
+            ;;
+
             "-h"|"--help") print_usage; exit ;;
             *)
                 : "${out:=string}"
@@ -838,10 +871,11 @@ main()
             "get_${function}"
     done
 
-    for i in "${!func[@]}"; do
-        [[ ! "${bat_info[${func[$i]}]}" ]] && \
-            unset 'func[$i]'
-    done
+    [[ ! "${str_format}" ]] && \
+        for i in "${!func[@]}"; do
+            [[ ! "${bat_info[${func[$i]}]}" ]] && \
+                unset 'func[$i]'
+        done
 
     [[ ! "${func[*]}" ]] && \
         exit 1
@@ -870,7 +904,23 @@ main()
             if [[ "${str_format}" ]]; then
                 out="${str_format}"
                 for function in "${func[@]}"; do
-                    out="${out/'{}'/${bat_info[${function}]}}"
+                    if [[ "${bat_info[${function}]}" ]]; then
+                        prev="${out}"
+                        out="${out/\{${function}\}/${bat_info[${function}]}}"
+
+                        [[ "${out}" == "${prev}" ]] && \
+                            out="${out/\{\}/${bat_info[${function}]}}"
+
+                        [[ "${str_format}" == *"${function}?"* ]] && {
+                            out="${out/\{${function}\?}"
+                            out="${out/'}'}"
+                        }
+                    else
+                        out="${out//\{${function}}"
+                        out="${out#*\}}"
+                        [[ "${str_format}" == *"${function}?"* ]] && \
+                            out="${out#*\}}"
+                    fi
                 done
                 printf "%s" "${out}"
             else
diff --git a/scripts/info/show_cpu b/scripts/info/show_cpu
--- a/scripts/info/show_cpu
+++ b/scripts/info/show_cpu
@@ -377,7 +377,7 @@ Examples:
     \$ ${0##*/} cpu cpu_usage
 
     Print CPU temperature and fan speed with a format string:
-    \$ ${0##*/} --format '{} | {}' temp fan
+    \$ ${0##*/} --format '{temp?{} | }{fan}'
 
 Misc:
     If notify-send is not installed, then the script will
@@ -393,7 +393,43 @@ get_args()
             "--stdout") : "${out:=stdout}" ;;
             "--json") : "${out:=json}" ;;
             "-r"|"--raw") : "${out:=raw}" ;;
-            "-f"|"--format") [[ "$2" ]] && { str_format="$2"; shift; } ;;
+            "-f"|"--format")
+                [[ "$2" ]] && {
+                    declare -A uniq
+
+                    : "${out:=string}"
+                    str_format="$2"
+
+                    tmp="${str_format}"
+                    regex_1='{([a-zA-Z]+)\?[^{]*{([a-zA-Z]+)}'
+                    regex_2='({)([a-zA-Z0-9_]+)'
+
+                    # First pass
+                    while [[ "${tmp}" =~ ${regex_1} ]]; do
+                        tmp="${tmp/${BASH_REMATCH[0]}}"
+                        [[ "${BASH_REMATCH[1]}" != "${BASH_REMATCH[2]}" ]] && {
+                            printf "Invalid format: %s != %s\\n" \
+                                   "${BASH_REMATCH[1]}" \
+                                   "${BASH_REMATCH[2]}" >&2
+                            exit 1
+                        }
+                    done
+
+                    tmp="${str_format}"
+
+                    # Second pass
+                    while [[ "${tmp}" =~ ${regex_2} ]]; do
+                        [[ ! "${uniq[${BASH_REMATCH[2]}]}" ]] && {
+                            uniq["${BASH_REMATCH[2]}"]="1"
+                            func+=("${BASH_REMATCH[2]}")
+                        }
+                        tmp="${tmp/${BASH_REMATCH[2]}}"
+                    done
+
+                    shift
+                }
+            ;;
+
             "-h"|"--help") print_usage; exit ;;
             *)
                 : "${out:=string}"
@@ -428,11 +464,13 @@ main()
     done
 
     # For every entry in func, check if the information returns an empty string
-    # and remove it
-    for i in "${!func[@]}"; do
-        [[ ! "${cpu_info[${func[$i]}]}" ]] && \
-            unset 'func[$i]'
-    done
+    # and remove it. Skip if using the '--format' option because we want to
+    # manually detect if there is an empty entry
+    [[ ! "${str_format}" ]] && \
+        for i in "${!func[@]}"; do
+            [[ ! "${cpu_info[${func[$i]}]}" ]] && \
+                unset 'func[$i]'
+        done
 
     # If there are no entries in func, then exit script
     [[ ! "${func[*]}" ]] && \
@@ -465,7 +503,23 @@ main()
             if [[ "${str_format}" ]]; then
                 out="${str_format}"
                 for function in "${func[@]}"; do
-                    out="${out/'{}'/${cpu_info[${function}]}}"
+                    if [[ "${cpu_info[${function}]}" ]]; then
+                        prev="${out}"
+                        out="${out/\{${function}\}/${cpu_info[${function}]}}"
+
+                        [[ "${out}" == "${prev}" ]] && \
+                            out="${out/\{\}/${cpu_info[${function}]}}"
+
+                        [[ "${str_format}" == *"${function}?"* ]] && {
+                            out="${out/\{${function}\?}"
+                            out="${out/'}'}"
+                        }
+                    else
+                        out="${out//\{${function}}"
+                        out="${out#*\}}"
+                        [[ "${str_format}" == *"${function}?"* ]] && \
+                            out="${out#*\}}"
+                    fi
                 done
                 printf "%s" "${out}"
             else
diff --git a/scripts/info/show_net b/scripts/info/show_net
--- a/scripts/info/show_net
+++ b/scripts/info/show_net
@@ -401,7 +401,7 @@ Examples:
     \$ ${0##*/} network_local_ip
 
     Print download and upload speed:
-    \$ ${0##*/} --format '{} | {}' network_download network_upload
+    \$ ${0##*/} --format '{network_download?{} | }{network_upload}'
 
 Misc:
     If notify-send is not installed, then the script will
@@ -416,7 +416,42 @@ get_args()
             "--stdout") : "${out:=stdout}" ;;
             "--json") : "${out:=json}" ;;
             "-r"|"--raw") : "${out:=raw}" ;;
-            "-f"|"--format") [[ "$2" ]] && { str_format="$2"; shift; } ;;
+            "-f"|"--format")
+                [[ "$2" ]] && {
+                    declare -A uniq
+
+                    : "${out:=string}"
+                    str_format="$2"
+
+                    tmp="${str_format}"
+                    regex_1='{([a-zA-Z]+)\?[^{]*{([a-zA-Z]+)}'
+                    regex_2='({)([a-zA-Z0-9_]+)'
+
+                    # First pass
+                    while [[ "${tmp}" =~ ${regex_1} ]]; do
+                        tmp="${tmp/${BASH_REMATCH[0]}}"
+                        [[ "${BASH_REMATCH[1]}" != "${BASH_REMATCH[2]}" ]] && {
+                            printf "Invalid format: %s != %s\\n" \
+                                   "${BASH_REMATCH[1]}" \
+                                   "${BASH_REMATCH[2]}" >&2
+                            exit 1
+                        }
+                    done
+
+                    tmp="${str_format}"
+
+                    # Second pass
+                    while [[ "${tmp}" =~ ${regex_2} ]]; do
+                        [[ ! "${uniq[${BASH_REMATCH[2]}]}" ]] && {
+                            uniq["${BASH_REMATCH[2]}"]="1"
+                            func+=("${BASH_REMATCH[2]}")
+                        }
+                        tmp="${tmp/${BASH_REMATCH[2]}}"
+                    done
+
+                    shift
+                }
+            ;;
             "-h"|"--help") print_usage; exit ;;
             *)
                 [[ ! "${out}" ]] && out="string"
@@ -445,10 +480,11 @@ main()
             "get_${function}"
     done
 
-    for i in "${!func[@]}"; do
-        [[ ! "${net_info[${func[$i]}]}" ]] && \
-            unset 'func[$i]'
-    done
+    [[ ! "${str_format}" ]] && \
+        for i in "${!func[@]}"; do
+            [[ ! "${net_info[${func[$i]}]}" ]] && \
+                unset 'func[$i]'
+        done
 
     [[ ! "${func[*]}" ]] && \
         exit 1
@@ -477,7 +513,23 @@ main()
             if [[ "${str_format}" ]]; then
                 out="${str_format}"
                 for function in "${func[@]}"; do
-                    out="${out/'{}'/${net_info[${function}]}}"
+                    if [[ "${net_info[${function}]}" ]]; then
+                        prev="${out}"
+                        out="${out/\{${function}\}/${net_info[${function}]}}"
+
+                        [[ "${out}" == "${prev}" ]] && \
+                            out="${out/\{\}/${net_info[${function}]}}"
+
+                        [[ "${str_format}" == *"${function}?"* ]] && {
+                            out="${out/\{${function}\?}"
+                            out="${out/'}'}"
+                        }
+                    else
+                        out="${out//\{${function}}"
+                        out="${out#*\}}"
+                        [[ "${str_format}" == *"${function}?"* ]] && \
+                            out="${out#*\}}"
+                    fi
                 done
                 printf "%s" "${out}"
             else
diff --git a/scripts/info/show_song b/scripts/info/show_song
--- a/scripts/info/show_song
+++ b/scripts/info/show_song
@@ -264,7 +264,7 @@ Examples:
     \$ ${0##*/} track
 
     Print current music player and state:
-    \$ ${0##*/} --format '{} | {}' app app_state
+    \$ ${0##*/} --format '{app} | {app_state}'
 
 Misc:
     If notify-send is not installed, then the script will
@@ -279,7 +279,42 @@ get_args()
             "--stdout") : "${out:=stdout}" ;;
             "--json") : "${out:=json}" ;;
             "-r"|"--raw") : "${out:=raw}" ;;
-            "-f"|"--format") [[ "$2" ]] && { str_format="$2"; shift; } ;;
+            "-f"|"--format")
+                [[ "$2" ]] && {
+                    declare -A uniq
+
+                    : "${out:=string}"
+                    str_format="$2"
+
+                    tmp="${str_format}"
+                    regex_1='{([a-zA-Z]+)\?[^{]*{([a-zA-Z]+)}'
+                    regex_2='({)([a-zA-Z0-9_]+)'
+
+                    # First pass
+                    while [[ "${tmp}" =~ ${regex_1} ]]; do
+                        tmp="${tmp/${BASH_REMATCH[0]}}"
+                        [[ "${BASH_REMATCH[1]}" != "${BASH_REMATCH[2]}" ]] && {
+                            printf "Invalid format: %s != %s\\n" \
+                                   "${BASH_REMATCH[1]}" \
+                                   "${BASH_REMATCH[2]}" >&2
+                            exit 1
+                        }
+                    done
+
+                    tmp="${str_format}"
+
+                    # Second pass
+                    while [[ "${tmp}" =~ ${regex_2} ]]; do
+                        [[ ! "${uniq[${BASH_REMATCH[2]}]}" ]] && {
+                            uniq["${BASH_REMATCH[2]}"]="1"
+                            func+=("${BASH_REMATCH[2]}")
+                        }
+                        tmp="${tmp/${BASH_REMATCH[2]}}"
+                    done
+
+                    shift
+                }
+            ;;
             "-h"|"--help") print_usage; exit ;;
             *)
                 : "${out:=string}"
@@ -304,10 +339,11 @@ main()
             "get_${function}"
     done
 
-    for i in "${!func[@]}"; do
-        [[ ! "${song_info[${func[$i]}]}" ]] && \
-            unset 'func[$i]'
-    done
+    [[ ! "${str_format}" ]] && \
+        for i in "${!func[@]}"; do
+            [[ ! "${song_info[${func[$i]}]}" ]] && \
+                unset 'func[$i]'
+        done
 
     [[ ! "${func[*]}" ]] && \
         exit 1
@@ -340,7 +376,23 @@ main()
             if [[ "${str_format}" ]]; then
                 out="${str_format}"
                 for function in "${func[@]}"; do
-                    out="${out/'{}'/${song_info[${function}]}}"
+                    if [[ "${song_info[${function}]}" ]]; then
+                        prev="${out}"
+                        out="${out/\{${function}\}/${song_info[${function}]}}"
+
+                        [[ "${out}" == "${prev}" ]] && \
+                            out="${out/\{\}/${song_info[${function}]}}"
+
+                        [[ "${str_format}" == *"${function}?"* ]] && {
+                            out="${out/\{${function}\?}"
+                            out="${out/'}'}"
+                        }
+                    else
+                        out="${out//\{${function}}"
+                        out="${out#*\}}"
+                        [[ "${str_format}" == *"${function}?"* ]] && \
+                            out="${out#*\}}"
+                    fi
                 done
                 printf "%s" "${out}"
             else
