Scripts: Cleanup and add support for more plugin managers in vim-plugins

diff --git a/scripts/utils/vim-plugins b/scripts/utils/vim-plugins
--- a/scripts/utils/vim-plugins
+++ b/scripts/utils/vim-plugins
@@ -18,15 +18,15 @@ trim()
     }
 }
 
+err()
+{
+    >&2 printf "\\e[31m%s\\e[0m%s\\n" "Error" ": $*"
+}
+
 get_vimrc()
 {
     [[ "${vimrc_file}" ]] && \
         return 0
-
-    vim_location=(
-        "${HOME}/.vimrc"
-        "${HOME}/.vim/vimrc"
-    )
 
     count="0"
 
@@ -42,87 +42,161 @@ get_plugin_manager()
         return 1
 
     mapfile -t vimrc_contents < "${vimrc_file}"
+    [[ "${plugin_managers[*]}" ]] && \
+        return 0
+
     count="0"
 
-    while [[ ! "${plugin}" ]] && ((++count < ${#vimrc_contents[@]})); do
+    while ((++count < ${#vimrc_contents[@]})); do
         line="${vimrc_contents[${count}]}"
         [[ ! "${line}" =~ ^\" ]] && \
             case "${vimrc_contents[${count}]}" in
-                *"pathogen#infect"*) plugin="pathogen" ;;
-                *"plug#begin"*) plugin="plug" ;;
-                *"vundle#begin"*) plugin="vundle" ;;
+                *"pathogen#infect"*) plugin_managers+=("pathogen") ;;
+                *"plug#begin"*) plugin_managers+=("plug") ;;
+                *"vundle#begin"*) plugin_managers+=("vundle") ;;
+                *"neobundle#begin"*) plugin_managers+=("neobundle") ;;
             esac
     done
 }
 
 get_plugins()
 {
-    [[ ! "${plugin}" || ! "${vimrc_contents[*]}" || ! "${vimrc_file}" ]] && \
+    [[ ! "${plugin_managers[*]}" \
+    || ! "${vimrc_contents[*]}" \
+    || ! "${vimrc_file}" ]] && \
         return 1
 
-    case "${plugin}" in
-        "pathogen")
-            count="0"
+    for i in "${plugin_managers[@]}"; do
+        case "${i,,}" in
+            "pathogen")
+                count="0"
 
-            while [[ ! "${pathogen_dir}" ]] && ((++count < ${#vimrc_contents[@]})); do
-                line="${vimrc_contents[${count}]}"
-                [[ "${line}" =~ ^runtime && "${line}" =~ pathogen ]] && {
-                    pathogen_dir="${line//runtime }"
-                    pathogen_dir="${vimrc_file%/*}/${pathogen_dir%%/*}"
-                }
-            done
-
-            [[ -d "${pathogen_dir}" ]] && \
-                for plugin_path in "${pathogen_dir}"/*; do
-                    plugin_name="${plugin_path##${pathogen_dir}/}"
-                    plugin_name="${plugin_name/.vim}"
-                    plugin_author="$(get_repo_author "${plugin_path}")"
-                    [[ "${plugin_name}" ]] && \
-                        plugins+=("${plugin_name},${plugin_author:-Unknown}")
+                while [[ ! "${pathogen_dir}" ]] && \
+                      ((++count < ${#vimrc_contents[@]})); do
+                    line="${vimrc_contents[${count}]}"
+                    [[ "${line}" =~ ^runtime && "${line}" =~ pathogen ]] && {
+                        pathogen_dir="${line//runtime }"
+                        pathogen_dir="${vimrc_file%/*}/${pathogen_dir%%/*}"
+                    }
                 done
-        ;;
 
-        "plug")
-            count="0"
-            unset start
-            unset end
+                if [[ -d "${pathogen_dir}" ]]; then
+                    for plugin_path in "${pathogen_dir}"/*; do
+                        plugin_name="${plugin_path##${pathogen_dir}/}"
+                        plugin_name="${plugin_name/.vim}"
+                        plugin_author="$(get_repo_author "${plugin_path}")"
+                        [[ "${plugin_name}" ]] && {
+                            temp="${plugin_name}"
+                            temp+=",${plugin_author:-Unknown}"
+                            temp+=",Pathogen"
+                            plugins+=("${temp}")
+                        }
+                    done
+                else
+                    err "Pathogen directory \"${pathogen_dir}\" does not exist"
+                fi
+            ;;
 
-            while [[ ! "${start}" || ! "${end}" ]] && ((++count < ${#vimrc_contents[@]})); do
-                line="${vimrc_contents[${count}]}"
-                [[ ! "${line}" =~ ^\" ]] && \
-                    case "${line}" in
-                        *"plug#begin"*) start="${count}" ;;
-                        *"plug#end"*) end="${count}" ;;
-                    esac
-            done
+            "plug")
+                count="0"
+                unset start
+                unset end
 
-            diff="$((end - start))"
-            for line in "${vimrc_contents[@]:${start}:${diff}}"; do
-                [[ "${line}" =~ ^Plug ]] && \
-                    if [[ "${line}" == *"|"* ]]; then
-                        IFS=$'\n' read -d "" -ra multi_plug <<< "${line//"|"/$'\n'}"
-                        for plug in "${multi_plug[@]}"; do
-                            plugins+=("$(process_plug "${plug}")")
-                        done
-                    else
-                        plugins+=("$(process_plug "${line}")")
-                    fi
-            done
-        ;;
-    esac
+                while [[ ! "${start}" || ! "${end}" ]] && \
+                      ((++count < ${#vimrc_contents[@]})); do
+                    line="${vimrc_contents[${count}]}"
+                    [[ ! "${line}" =~ ^\" ]] && \
+                        case "${line}" in
+                            *"plug#begin"*) start="${count}" ;;
+                            *"plug#end"*) end="${count}" ;;
+                        esac
+                done
+
+                diff="$((end - start))"
+                for line in "${vimrc_contents[@]:${start}:${diff}}"; do
+                    [[ "${line}" =~ ^Plug ]] && \
+                        if [[ "${line}" == *"|"* ]]; then
+                            IFS=$'\n' read -d "" -ra multi_plug \
+                                <<< "${line//"|"/$'\n'}"
+                            for plug in "${multi_plug[@]}"; do
+                                temp="$(process_plug "${plug}")"
+                                temp+=",Vim-Plug"
+                                plugins+=("${temp}")
+                            done
+                        else
+                            temp="$(process_plug "${line}")"
+                            temp+=",Vim-Plug"
+                            plugins+=("${temp}")
+                        fi
+                done
+            ;;
+
+            "vundle")
+                count="0"
+                unset start
+                unset end
+
+                while [[ ! "${start}" || ! "${end}" ]] && \
+                      ((++count < ${#vimrc_contents[@]})); do
+                    line="${vimrc_contents[${count}]}"
+                    [[ ! "${line}" =~ ^\" ]] && \
+                        case "${line}" in
+                            *"vundle#begin"*) start="${count}" ;;
+                            *"vundle#end"*) end="${count}" ;;
+                        esac
+                done
+
+                diff="$((end - start))"
+                for line in "${vimrc_contents[@]:${start}:${diff}}"; do
+                    [[ "${line}" =~ ^Plugin ]] && {
+                        temp="$(process_plug "${line}")"
+                        temp+=",Vundle"
+                        plugins+=("${temp}")
+                    }
+                done
+            ;;
+
+            "neobundle")
+                count="0"
+                unset start
+                unset end
+
+                while [[ ! "${start}" || ! "${end}" ]] && \
+                      ((++count < ${#vimrc_contents[@]})); do
+                    line="${vimrc_contents[${count}]}"
+                    [[ ! "${line}" =~ ^\" ]] && \
+                        case "${line}" in
+                            *"neobundle#begin"*) start="${count}" ;;
+                            *"neobundle#end"*) end="${count}" ;;
+                        esac
+                done
+
+                diff="$((end - start))"
+                for line in "${vimrc_contents[@]:${start}:${diff}}"; do
+                    [[ "${line}" =~ ^NeoBundle ]] && \
+                        plugins+=("$(process_plug "${line}"),NeoBundle")
+                done
+            ;;
+        esac
+    done
 }
 
 get_repo_author()
 {
-    { [[ -d "$1/.git" ]] || git -C "$1" rev-parse --git-dir > /dev/null 2>&1; } && {
-        mapfile -t first_commit < <(git -C "$1" rev-list --max-parents=0 HEAD)
-        mapfile -t git_log < <(git -C "$1" log "${first_commit[0]}")
-        author="${git_log[1]}"
-        author="${author//Author: }"
-        author="${author%%<*}"
-        author="${author/<}"
-        author="$(trim "${author}")"
-        printf "%s" "${author}"
+    { \
+        [[ -d "$1/.git" ]] || \
+        git -C "$1" rev-parse --git-dir > /dev/null 2>&1; } && {
+            mapfile -t first_commit < <(
+                git -C "$1" rev-list --max-parents=0 HEAD
+            )
+
+            mapfile -t git_log < <(git -C "$1" log "${first_commit[0]}")
+            author="${git_log[1]}"
+            author="${author//Author: }"
+            author="${author%%<*}"
+            author="${author/<}"
+            author="$(trim "${author}")"
+            printf "%s" "${author}"
     }
 }
 
@@ -138,10 +212,12 @@ process_plug()
     plugin_name="$(trim_string "${plugin##*/}")"
     plugin_author="$(trim_string "${plugin%%/*}")"
 
-    [[ "${plugin_author}" =~ ^\~ ]] && {
+    if [[ "${plugin_author}" =~ ^\~ ]]; then
         plugin_name="${plugin}"
         plugin_author="Unmanaged"
-    }
+    elif [[ "${plugin_author}" =~ (git|file): ]]; then
+        plugin_author="Unmanaged"
+    fi
 
     [[ "${plugin_name}" ]] && \
         printf "%s" "${plugin_name},${plugin_author:-Unknown}"
@@ -152,33 +228,91 @@ print_plugins()
     [[ ! "${plugins[*]}" ]] && \
         return 1
 
-    name_arr+=("Plugin Name")
-    author_arr+=("Author")
+    plugins=("Plugin Name,Author,Manager" "${plugins[@]}")
 
     for i in "${plugins[@]}"; do
-        IFS=$'\n' read -d "" -r name author <<< "${i//,/$'\n'}"
+        IFS=$'\n' read -d "" -r name author manager <<< "${i//,/$'\n'}"
 
-        line_length="${#name}"
-        ((line_length >= ${padding:=0})) && {
-            padding="${#name}"
-            max_line=$((${#name} + ${#author} + 3))
-        }
+        name_length="${#name}"
+        ((name_length >= ${name_padding:=0})) && \
+            name_padding="${name_length}"
+
+        manager_length="${#manager}"
+        ((manager_length >= ${manager_padding:=0})) && \
+            manager_padding="${manager_length}"
+
+        author_length="${#author}"
+        ((author_length >= ${author_padding:=0})) && \
+            author_padding="${author_length}"
 
         name_arr+=("${name}")
+        manager_arr+=("${manager}")
         author_arr+=("${author}")
     done
 
     for ((i = 0; i < ${#plugins[@]}; i++)); do
-        printf -v "out[$i]" "%-${padding}s %s %s" "${name_arr[$i]}" "|" "${author_arr[$i]}"
+        printf -v "col_1" "%-${name_padding}s %s" "${name_arr[$i]}" "|"
+        printf -v "col_2" "%-${manager_padding}s %s" "${manager_arr[$i]}" "|"
+        printf -v "col_3" "%-${author_padding}s" "${author_arr[$i]}"
+        out[$i]="${col_1} ${col_2} ${col_3}"
     done
+
+    max_line="${#out[0]}"
 
     eval printf -v line "%0.s=" "{1..${max_line}}"
     printf "%s\\n" "${line}" "${out[0]}" "${line}"
     printf "%s\\n" "${out[@]:1}"
 }
 
+show_usage()
+{
+    printf "%s\\n" "
+Usage: ${0##*/} -o option --option \"value\"
+
+    Options:
+
+    [-u|--vimrc \"/path/to/vimrc\"]       Use a user specified vimrc
+    [-p|--plugin-manager \"name\"]        Show plugins used by a plugin manager
+    [-h|--help]                         Show this message
+
+    Supported managers:
+        - pathogen
+        - plug
+        - vundle
+        - neobundle
+"
+    printf "%s\\n" "    Checking these locations for vimrc file:"
+    for file in "${vim_location[@]}"; do
+        printf "%s\\n" "        - ${file}"
+    done
+    printf "\\n"
+}
+
+get_args()
+{
+    while (($# > 0)); do
+        case "$1" in
+            "-u"|"--vimrc") vimrc_file="$2"; shift ;;
+            "-p"|"--plugin-manager") plugin_managers+=("$2"); shift ;;
+            "-h"|"--help") show_usage; exit 0 ;;
+        esac
+        shift
+    done
+
+    [[ "${vimrc_file}" && ! -f "${vimrc_file}" ]] && {
+        err "Selected vimrc file \"${vimrc_file}\" is not valid"
+        exit 1
+    }
+}
+
 main()
 {
+    vim_location=(
+        "${HOME}/.vimrc"
+        "${HOME}/.vim/vimrc"
+    )
+
+    get_args "$@"
     get_vimrc
     get_plugin_manager
     get_plugins
